# Generated by Django 4.2 on 2023-10-04 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='LesJoureDeTravaille',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='employees',
            name='Npassport',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='employees',
            name='totalmadakhil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='typeofvisa',
            field=models.CharField(choices=[('في انتضار الدفع', 'في انتضار الدفع'), ('ينتضر القبول', 'ينتضر القبول'), ('ينتضر الدعوة', 'ينتضر الدعوة'), ('ينتضر الاستفبال في المطار', 'ينتضر الاستفبال في المطار')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='timage',
            field=models.ImageField(upload_to=''),
        ),
    ]
