# Generated by Django 4.2 on 2023-10-16 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_employees_lesjouredetravaille_employees_npassport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='LePaimentDeClient',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250000)]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='typeofvisa',
            field=models.CharField(choices=[('في انتضار الدفع', 'في انتضار الدفع'), ('ينتضر القبول', 'ينتضر القبول'), ('ينتضر الدعوة', 'ينتضر الدعوة'), ('ينتضر الاستفبال في المطار', 'ينتضر الاستفبال في المطار'), ('وصل', 'وصل')], default='', max_length=100),
        ),
    ]
